module.exports = {
  plugins: ['stylelint-scss', 'stylelint-order'],
  extends: 'stylelint-config-prettier',
  rules: {
    'length-zero-no-unit': true,
    'function-calc-no-invalid': true,
    'string-no-newline': true,
    'property-no-unknown': true,
    'function-calc-no-unspaced-operator': true,
    'order/properties-alphabetical-order': true,
    'scss/at-else-if-parentheses-space-before': 'always',
    'scss/at-if-closing-brace-newline-after': 'always-last-in-chain',
    'scss/at-else-closing-brace-newline-after': 'always-last-in-chain',
    'scss/at-if-closing-brace-space-after': 'always-intermediate',
    'scss/at-else-closing-brace-space-after': 'always-intermediate',
    'scss/at-else-empty-line-before': 'never',
    'at-rule-empty-line-before': ['always', { ignoreAtRules: 'else' }],
    'scss/at-extend-no-missing-placeholder': true,
    'scss/at-function-named-arguments': 'always',
    'scss/at-mixin-named-arguments': 'always',
    'scss/at-mixin-parentheses-space-before': 'always',
    'scss/at-function-parentheses-space-before': 'always',
    'scss/double-slash-comment-empty-line-before': 'always',
    'scss/double-slash-comment-whitespace-inside': 'always',
    'scss/at-mixin-pattern': /.+/,
    'scss/at-function-pattern': /.+/,
    'scss/percent-placeholder-pattern': /.+/,
    'scss/at-mixin-argumentless-call-parentheses': 'always',
    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': true,
    'scss/operator-no-newline-after': true,
    'scss/operator-no-newline-before': true,
    'scss/operator-no-unspaced': true,
    'scss/dollar-variable-colon-newline-after': 'always-multi-line',
    'scss/dollar-variable-colon-space-after': 'always-single-line',
    'scss/dollar-variable-colon-space-before': 'never',
  },
}
